# Generated by Django 5.2.3 on 2025-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprice',
            options={},
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='grade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='variety',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_rainfall', models.FloatField()),
                ('agency_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('state', 'district', 'date')},
            },
        ),
    ]
