# Generated by Django 5.2.3 on 2025-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_alter_marketprice_options_alter_marketprice_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='e.g., Wheat, Rice, Tomato', max_length=100)),
                ('advisory_type', models.CharField(choices=[('DISEASE', 'Disease Alert'), ('PEST', 'Pest Alert'), ('BEST_PRACTICE', 'Best Practice Advisory'), ('GENERAL', 'General Advisory')], default='GENERAL', max_length=20)),
                ('title', models.CharField(help_text='Concise title for the advisory', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue or advice')),
                ('recommendation', models.TextField(blank=True, help_text='Recommended actions or solutions', null=True)),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Crop Advisories',
                'ordering': ['-date_published'],
            },
        ),
    ]
