# Generated by Django 5.2.3 on 2025-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_farmerdiaryentry_alter_rainfalldata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropadvisory',
            options={'ordering': ['-date_published', '-severity'], 'verbose_name_plural': 'Crop Advisories'},
        ),
        migrations.AlterModelOptions(
            name='marketprice',
            options={'verbose_name_plural': 'Market Prices'},
        ),
        migrations.AddField(
            model_name='cropadvisory',
            name='alert_type',
            field=models.CharField(choices=[('Weather', 'Weather Alert'), ('Pest', 'Pest Outbreak'), ('Disease', 'Disease Warning'), ('Price', 'Price Trend Alert'), ('General', 'General Advisory'), ('Fertilizer', 'Fertilizer Advisory'), ('Irrigation', 'Irrigation Advisory')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='cropadvisory',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location or region for the advisory', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cropadvisory',
            name='severity',
            field=models.CharField(choices=[('Green', 'Informational'), ('Yellow', 'Warning'), ('Red', 'Critical')], default='Green', max_length=20),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='unit',
            field=models.CharField(default='Quintal', max_length=50),
        ),
        migrations.AlterField(
            model_name='cropadvisory',
            name='crop_name',
            field=models.CharField(blank=True, help_text='e.g., Wheat, Rice, Tomato', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
