# Generated by Django 5.2.3 on 2025-08-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_alter_cropadvisory_options_alter_marketprice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropadvisory',
            options={'ordering': ['-published_month', '-severity'], 'verbose_name_plural': 'Crop Advisories'},
        ),
        migrations.RemoveField(
            model_name='cropadvisory',
            name='date_published',
        ),
        migrations.AddField(
            model_name='cropadvisory',
            name='published_month',
            field=models.CharField(default='August', help_text='The month the advisory was published.', max_length=20),
        ),
    ]
